# Generated by Django 4.2.7 on 2024-10-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evaluate", "0002_alter_result_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="option",
            old_name="question_id",
            new_name="question",
        ),
        migrations.RenameField(
            model_name="question",
            old_name="scale_id",
            new_name="scale",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="scale_id",
            new_name="scale",
        ),
    ]
