# Generated by Django 4.2.7 on 2024-10-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluate", "0003_rename_question_id_option_question_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scale",
            name="description",
            field=models.TextField(help_text="量表描述", verbose_name="量表描述"),
        ),
    ]
