# Generated by Django 4.2.7 on 2024-10-30 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evaluate", "0004_alter_scale_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="option",
            name="score",
            field=models.IntegerField(
                default=1, help_text="选项分数", verbose_name="选项分数"
            ),
        ),
        migrations.AlterField(
            model_name="option",
            name="question",
            field=models.ForeignKey(
                db_constraint=False,
                default=1,
                help_text="关联题目",
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluate.question",
                verbose_name="所属题目",
            ),
            preserve_default=False,
        ),
    ]
