# Generated by Django 4.2.7 on 2024-11-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="identity_card",
            field=models.CharField(
                default="", help_text="身份证", max_length=18, verbose_name="身份证"
            ),
        ),
    ]
